name: 'Build wheels'
description: 'Build wheels using cibuildwheel'
runs:
  using: "composite"
  steps:
    - name: Upgrade pip
      run: python -m pip install pip --upgrade
    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel
    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
    - uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl
